# Generated by Django 2.1 on 2018-12-14 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jokbo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admit', models.TextField(blank=True, choices=[('파일 검토 중', '파일 검토 중'), ('허가', '허가')], null=True, verbose_name='다시 먹을 지 여부')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='족보 파일')),
                ('department', models.TextField(blank=True, verbose_name='00대학')),
                ('major', models.TextField(blank=True, verbose_name='전공')),
                ('subject', models.TextField(blank=True, verbose_name='강의명')),
                ('year', models.IntegerField(blank=True, choices=[(2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019')], null=True, verbose_name='년도')),
                ('semester', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2')], null=True, verbose_name='학기')),
                ('term', models.CharField(blank=True, choices=[('중간', '중간'), ('기말', '기말'), ('기타', '기타')], max_length=2, null=True, verbose_name='중간/기말/기타')),
                ('grade', models.IntegerField(blank=True, choices=[(1, '1'), (2.5, '2~3'), (4, '4')], null=True, verbose_name='학년')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
    ]
