<<<<<<< HEAD
# Generated by Django 2.1 on 2018-12-20 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asitis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='과목명')),
                ('professor', models.CharField(blank=True, max_length=16, null=True, verbose_name='교수명')),
                ('code', models.CharField(max_length=8, verbose_name='과목코드')),
                ('department', models.CharField(max_length=16, verbose_name='소속 대학명')),
                ('major', models.CharField(max_length=16, verbose_name='전공')),
                ('grade', models.CharField(max_length=8, verbose_name='수강 학년')),
                ('semester', models.TextField(verbose_name='학기')),
            ],
        ),
        migrations.RemoveField(
            model_name='jokbo',
            name='department',
        ),
        migrations.RemoveField(
            model_name='jokbo',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='jokbo',
            name='major',
        ),
        migrations.RemoveField(
            model_name='jokbo',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='jokbo',
            name='term',
        ),
        migrations.RemoveField(
            model_name='jokbo',
            name='year',
        ),
        migrations.AlterField(
            model_name='jokbo',
            name='admit',
            field=models.TextField(blank=True, choices=[('파일 검토 중', '파일 검토 중'), ('허가', '허가')], null=True, verbose_name='허가 여부'),
        ),
        migrations.AlterField(
            model_name='jokbo',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asitis.Subject', verbose_name='해당 수업'),
        ),
    ]
=======
# Generated by Django 2.1 on 2018-12-20 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asitis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='과목명')),
                ('professor', models.CharField(blank=True, max_length=16, null=True, verbose_name='교수명')),
                ('code', models.CharField(max_length=8, verbose_name='과목코드')),
                ('department', models.CharField(max_length=16, verbose_name='소속 대학명')),
                ('major', models.CharField(max_length=16, verbose_name='전공')),
                ('grade', models.CharField(max_length=8, verbose_name='수강 학년')),
                ('semester', models.TextField(verbose_name='학기')),
            ],
        ),
        migrations.RemoveField(
            model_name='jokbo',
            name='department',
        ),
        migrations.RemoveField(
            model_name='jokbo',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='jokbo',
            name='major',
        ),
        migrations.RemoveField(
            model_name='jokbo',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='jokbo',
            name='term',
        ),
        migrations.RemoveField(
            model_name='jokbo',
            name='year',
        ),
        migrations.AlterField(
            model_name='jokbo',
            name='admit',
            field=models.TextField(blank=True, choices=[('파일 검토 중', '파일 검토 중'), ('허가', '허가')], null=True, verbose_name='허가 여부'),
        ),
        migrations.AlterField(
            model_name='jokbo',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asitis.Subject', verbose_name='해당 수업'),
        ),
    ]
>>>>>>> bfc488ad51715cf21e4e02fbe4765263f013a6aa
