# Generated by Django 2.1 on 2018-12-21 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asitis', '0003_subject_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jokbo',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
