# Generated by Django 2.1 on 2018-12-21 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asitis', '0004_auto_20181221_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='과목명')),
                ('professor', models.CharField(blank=True, max_length=16, null=True, verbose_name='교수명')),
                ('code', models.CharField(max_length=8, verbose_name='과목코드')),
                ('department', models.CharField(max_length=16, verbose_name='소속 대학명')),
                ('major', models.CharField(max_length=16, verbose_name='전공')),
                ('course', models.CharField(max_length=8, verbose_name='교양/전공 여부')),
                ('grade', models.CharField(max_length=8, verbose_name='수강 학년')),
                ('semester', models.TextField(verbose_name='학기')),
            ],
        ),
        migrations.AddField(
            model_name='jokbo',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='asitis.Subject', verbose_name='해당 수업'),
            preserve_default=False,
        ),
    ]
