<<<<<<< HEAD
# Generated by Django 2.1 on 2018-12-18 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=30, verbose_name='소식 받을 이메일')),
                ('telegram_id', models.CharField(blank=True, max_length=30, verbose_name='소식 받을 텔레그램')),
                ('tags', models.TextField(blank=True, verbose_name='공지 선택 태그')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
        ),
    ]
=======
# Generated by Django 2.1 on 2018-12-18 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=30, verbose_name='소식 받을 이메일')),
                ('telegram_id', models.CharField(blank=True, max_length=30, verbose_name='소식 받을 텔레그램')),
                ('tags', models.TextField(blank=True, verbose_name='공지 선택 태그')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
        ),
    ]
>>>>>>> bfc488ad51715cf21e4e02fbe4765263f013a6aa
